spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db2409?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.azhe.pojo


knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
  group:
    default:
      group-name: default
      api-rule: package
      api-rule-resources:
        - com.azhe.controller
